name: Job Output Demo

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      app_version: ${{ steps.version_step.outputs.version }}

    steps:
      - name: Generate version
        id: version_step
        run: |
          echo "version=1.0.5" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Use build output
        run: echo "Deploying version ${{ needs.build.outputs.app_version }}"
